system {
    host-name branch-sd01;
}

interfaces {
    irb {
        unit 10 {
            description "USERS-VLAN";
            family inet {
                address 10.10.10.1/24;
            }
        }

        unit 20 {
            description "SERVERS-VLAN";
            family inet {
                address 10.20.20.1/24;
            }
        }
    }
}
